spring:
  jpa:
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        "[show_sql]": true
        "[format_sql]": true
        "[highlight_sql]": true
        "[use_sql_comments]": true
logging:
  level:
    "[org.hibernate.sql]": debug
    "[org.hibernate.type.descriptor.sql]": trace
